### ISSUE TITLE
LIT3117RepCh397 and LIT1834Mahlet (Mahleta sege doublet?)

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#2652] opened 2024-09-27 10:06 UTC
LIT3117RepCh397 - is it the same as LIT1834Mahlet or just a part of it? 
I believe it is a doublet; I would delete LIT3117RepCh397 
@smaugustine @DenisNosnitsin1970 can you have a look at
https://betamasaheft.eu/BLorient578
https://betamasaheft.eu/BLorient581
https://betamasaheft.eu/EMIP00017 ?
Thank you!
@karljonaskarlsson @CarstenHoffmannMarburg

**Comment by smaugustine** [comment] 2024-09-27 13:52
I am certain that it is also a duplicate of `LIT1865Malkea`. Habtemichael mentions the title in some entries in the EAe, esp. e.g. '[it is] presumably a poetic adaptation of the Māḫleta ṣəge' but the only manuscripts he ever lists as witnessing it contain Māḫleta ṣəge as usual. I have seen the title also written in manuscripts, but again it is simply an alternate title for Māḫleta ṣəge and not a distinct text.

**Closed as completed** 2024-09-27 18:23 UTC
